-- ============================================================================
-- restaurantfriend — migration 153 · batch logs are generated BY SCHEDULE
--
-- Mark, 2026-09-30: "Elements can be associated with a 'schedule' … Weekly,
-- Donut, and Ice Cream. Each element gets associated with one of them. When
-- creating a new batch log, we then choose the schedule instead of the element
-- types." And: "batch logs should track and display which schedule they came
-- from." AB "is no longer a thing". Ice cream elements go to Ice Cream.
--
-- What it is for first: the opening and mid shift reports record how many
-- BATCHES of each donut the bakers made, per kitchen per day. That page
-- generates the kitchen's DONUT log when it is reached and asks for one number
-- per element — `production_batches.batch_count`, a total (7.5 is real).
--
--   1. `production_elements.schedule_class` becomes a closed vocabulary —
--      WEEKLY · DONUT · ICE CREAM, uppercase (lib/production's reason). "Donut"
--      is folded into DONUT, AB is cleared, and every element typed Ice Cream
--      or Ice Cream Cup moves to ICE CREAM.
--   2. `production_element_locations.on_weekly_log` and its three siblings are
--      renamed `on_batch_log` / `batch_sort` / `batch_amount` / `batch_unit`:
--      whether a kitchen makes an element on ITS schedule's log, whichever
--      schedule that is. The membership stays per kitchen — DF01 stocks 70
--      elements and generates 26 — so it cannot be derived from the schedule.
--   3. `production_batch_logs.schedule`, and the one-log-per-kitchen-per-day
--      key becomes one per kitchen, day AND schedule, so a Weekly log and a
--      Donut log can share a morning. NULL is a FileMaker log: those mixed
--      every schedule on one day, so they keep the old (kitchen, day) key.
--      The five logs this app generated were all Weekly and are marked so.
--   4. `batch_count` on `production_batches` and on `shift_report_batches`,
--      the draft 070 flushes.
--   5. `generate_production_batches(location, date, schedule, replace)` —
--      dropped and recreated, since the argument list changes (033/047).
--   6. `submit_shift_report` writes the count; `reopen_shift_report` takes it
--      back. Both restated IN FULL from 087 and 107 (055's rule), changed only
--      in the blocks marked 153.
--   7. Data: the eight donuts Mark named go on the batch log at DF01 and DF02.
--
-- Depends on 045–047, 070, 087, 107. NOT rerunnable (the renames).
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. The schedule vocabulary
-- ----------------------------------------------------------------------------
update production_elements
   set schedule_class = upper(btrim(schedule_class))
 where schedule_class is distinct from upper(btrim(schedule_class));

update production_elements set schedule_class = null where schedule_class = 'AB';

update production_elements
   set schedule_class = 'ICE CREAM'
 where lower(btrim(element_type)) in ('ice cream', 'ice cream cup');

alter table production_elements
  add constraint production_elements_schedule_class_check
  check (schedule_class in ('WEEKLY', 'DONUT', 'ICE CREAM'));


-- ----------------------------------------------------------------------------
-- 2. A kitchen's batch-log membership, no longer only weekly
-- ----------------------------------------------------------------------------
alter table production_element_locations rename column on_weekly_log to on_batch_log;
alter table production_element_locations rename column weekly_sort   to batch_sort;
alter table production_element_locations rename column weekly_amount to batch_amount;
alter table production_element_locations rename column weekly_unit   to batch_unit;
alter index production_element_locations_weekly_idx
  rename to production_element_locations_batch_idx;


-- ----------------------------------------------------------------------------
-- 3. Which schedule a log came from
-- ----------------------------------------------------------------------------
alter table production_batch_logs
  add column schedule text check (schedule in ('WEEKLY', 'DONUT', 'ICE CREAM'));

update production_batch_logs set schedule = 'WEEKLY' where legacy_id is null;

alter table production_batch_logs
  drop constraint production_batch_logs_location_id_log_date_key;

create unique index production_batch_logs_schedule_day
  on production_batch_logs (location_id, log_date, schedule)
  where schedule is not null;

-- FileMaker's days: one mixed log per kitchen per day, as before.
create unique index production_batch_logs_legacy_day
  on production_batch_logs (location_id, log_date)
  where schedule is null;


-- ----------------------------------------------------------------------------
-- 4. The day's total
-- ----------------------------------------------------------------------------
-- (10,2) holds a half or a quarter batch, which the bakers really make.
alter table production_batches
  add column batch_count numeric(10,2) check (batch_count is null or batch_count >= 0);

alter table shift_report_batches
  add column batch_count numeric(10,2) check (batch_count is null or batch_count >= 0);


-- ----------------------------------------------------------------------------
-- 5. Generation, by schedule
-- ----------------------------------------------------------------------------
drop function if exists public.generate_production_batches(uuid, date, boolean, text[]);

create function public.generate_production_batches(
  p_location_id  uuid,
  p_log_date     date,
  -- WHICH SCHEDULE (153): 'WEEKLY', 'DONUT' or 'ICE CREAM'. Required — a
  -- log is one schedule's, so there is no "every schedule".
  p_schedule     text,
  p_replace      boolean default false
) returns jsonb
language plpgsql
-- SECURITY INVOKER, 013's precedent: every insert flows through the policies
-- above, which is also what lets a supervisor run it. The batch-number sequence
-- is the one thing invoker cannot reach, so numbers come from 044's definer.
set search_path = public
as $$
declare
  v_org      uuid;
  v_loc_code text;
  v_log_id   uuid;
  v_created_log boolean := false;
  v_existing uuid;
  v_number   text;
  v_version_id    uuid;
  v_version_label text;
  v_created  jsonb := '[]'::jsonb;
  v_skipped  jsonb := '[]'::jsonb;
  v_warnings jsonb := '[]'::jsonb;
  d          record;
  w          record;
begin
  if p_log_date is null then
    raise exception 'no date given';
  end if;

  if p_schedule is null or p_schedule not in ('WEEKLY', 'DONUT', 'ICE CREAM') then
    raise exception 'unknown schedule %', coalesce(p_schedule, '(none)');
  end if;

  select l.org_id, l.code into v_org, v_loc_code
    from locations l where l.id = p_location_id;

  if v_org is null then
    raise exception 'unknown location %', p_location_id;
  end if;

  if not user_has_role(v_org, array['owner', 'admin', 'purchaser', 'supervisor']) then
    raise exception 'insufficient role to generate a batch log';
  end if;

  -- The log for that day, made if it isn't there. Generating twice TOPS UP one
  -- log rather than making a second — the unique index says so and this is how
  -- it is honoured.
  select id into v_log_id
    from production_batch_logs
   where location_id = p_location_id and log_date = p_log_date
     and schedule = p_schedule;

  if v_log_id is null then
    insert into production_batch_logs (org_id, location_id, log_date, schedule, generated_by)
    values (v_org, p_location_id, p_log_date, p_schedule, auth.uid())
    returning id into v_log_id;
    v_created_log := true;
  end if;

  -- Named once, before the loop: an element on the round with no master recipe
  -- still generates — the batch is real and somebody will make it from memory —
  -- but it is what a baker most wants to hear about.
  for w in
    select e.name as element_name
      from production_element_locations el
      join production_elements e on e.id = el.element_id
     where el.location_id = p_location_id
       and el.on_batch_log
       and el.is_active
       and e.is_active
       and e.kind = 'made'
       -- The same filter the generating loop uses.
       and e.schedule_class = p_schedule
       and not exists (
         select 1
           from production_recipe_versions v
           join production_recipes r on r.id = v.recipe_id
          where r.element_id = e.id and v.is_master
       )
     order by e.name
  loop
    v_warnings := v_warnings || jsonb_build_object(
      'kind', 'no_master_recipe', 'element_name', w.element_name);
  end loop;

  -- ONE TABLE, at the grain the fact actually has. No weekday, no shift, no
  -- collapse — `production_element_locations` is already one row per
  -- (element, kitchen).
  for d in
    select el.element_id,
           el.batch_sort,
           el.batch_amount,
           el.batch_unit,
           el.stock_count,
           el.stock_size,
           el.stock_unit,
           e.name as element_name
      from production_element_locations el
      join production_elements e on e.id = el.element_id
     where el.location_id = p_location_id
       and el.on_batch_log
       and el.is_active
       and e.is_active
       -- The element's SCHEDULE (153), where 047 filtered by element type.
       and e.schedule_class = p_schedule
     order by el.batch_sort nulls last, e.name
  loop
    select b.id into v_existing
      from production_batches b
     where b.log_id = v_log_id
       and b.element_id = d.element_id
       and b.is_generated;

    if v_existing is not null and not p_replace then
      v_skipped := v_skipped || jsonb_build_object(
        'batch_id', v_existing, 'element_name', d.element_name, 'reason', 'exists');
      continue;
    end if;

    select v.id, v.version_label
      into v_version_id, v_version_label
      from production_recipe_versions v
      join production_recipes r on r.id = v.recipe_id
     where r.element_id = d.element_id and v.is_master
     limit 1;

    if v_existing is null then
      v_number := public.next_batch_number(p_location_id);

      insert into production_batches (
        org_id, log_id, element_id, location_id, is_generated,
        batch_number, sort,
        created_by, recipe_version_id, recipe_version_label,
        batch_amount, batch_unit,
        par_count, par_size, par_unit, status)
      values (
        v_org, v_log_id, d.element_id, p_location_id, true,
        v_number, d.batch_sort,
        auth.uid(), v_version_id, v_version_label,
        d.batch_amount, d.batch_unit,
        d.stock_count, d.stock_size, d.stock_unit, 'to_do');

      v_created := v_created || jsonb_build_object(
        'element_name', d.element_name, 'batch_number', v_number);
    else
      -- REPLACE refreshes what the round says and leaves every measured thing
      -- alone: status, on-hand, yield, notes, photo, operator and the cost
      -- snapshot are untouched. There is no yield guard here, unlike 044's:
      -- nothing this rewrites can destroy a measurement.
      update production_batches
         set sort                 = d.batch_sort,
             batch_amount         = d.batch_amount,
             batch_unit           = d.batch_unit,
             par_count            = d.stock_count,
             par_size             = d.stock_size,
             par_unit             = d.stock_unit,
             recipe_version_id    = v_version_id,
             recipe_version_label = v_version_label
       where id = v_existing;
    end if;
  end loop;

  return jsonb_build_object(
    'log_id',        v_log_id,
    'log_date',      p_log_date,
    'new_log',       v_created_log,
    'location_id',   p_location_id,
    'location_code', v_loc_code,
    'schedule',      p_schedule,
    'created',       v_created,
    'skipped',       v_skipped,
    'warnings',      v_warnings);
end;
$$;

-- 047 left these out, so its function was executable by `anon` through
-- Supabase's default privileges. Stated by name, CLAUDE.md's rule.
revoke all on function public.generate_production_batches(uuid, date, text, boolean) from public;
revoke all on function public.generate_production_batches(uuid, date, text, boolean) from anon;
grant execute on function public.generate_production_batches(uuid, date, text, boolean) to authenticated;


-- ----------------------------------------------------------------------------
-- 6. The shift report writes the count, and reopening takes it back
-- ----------------------------------------------------------------------------

create or replace function public.submit_shift_report(p_report_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report      shift_reports%rowtype;
  v_rating      record;
  v_count       record;
  v_batch       record;
  v_event_id    uuid;
  v_ratings     integer := 0;
  v_breaks      integer := 0;
  v_counts      integer := 0;
  v_batches     integer := 0;
  v_skipped     jsonb := '[]'::jsonb;
  v_name        text;
begin
  select * into v_report from shift_reports where id = p_report_id;

  if v_report.id is null then
    raise exception 'No such shift report';
  end if;

  -- What the SELECT policy would have allowed.
  if v_report.org_id not in (select user_org_ids()) then
    raise exception 'Not your organisation';
  end if;

  if not user_has_role(v_report.org_id,
                       array['owner', 'admin', 'purchaser', 'supervisor']) then
    raise exception 'insufficient role to send a shift report';
  end if;

  -- AND it must be YOUR draft. Found on the harness: with only the role check
  -- above, one supervisor could send a colleague's half-written report while
  -- the UPDATE policy forbade them from so much as fixing a typo in it. A
  -- definer has to re-check what RLS would have, and RLS here says the author.
  -- Owner/admin are exempt because the table's own policy exempts them, which
  -- is also the only way to rescue a draft left by somebody who has left.
  if v_report.created_by is distinct from auth.uid()
     and not user_has_role(v_report.org_id, array['owner', 'admin']) then
    raise exception 'That report belongs to somebody else';
  end if;

  -- Idempotence. Sending twice would insert a second rating for every employee
  -- and re-stamp counts somebody may since have corrected by hand.
  if v_report.status <> 'draft' then
    raise exception 'That report was already sent on %',
      to_char(v_report.sent_at, 'YYYY-MM-DD HH24:MI');
  end if;

  -- ---- ratings → employee_events ------------------------------------------
  for v_rating in
    select * from shift_report_ratings
     where report_id = p_report_id
     order by created_at
  loop
    -- A row somebody added and left blank is not a rating. Skipping quietly is
    -- right here: an empty row is a mistake being abandoned, not a failure.
    if v_rating.score is null
       and coalesce(btrim(v_rating.note), '') = ''
       and v_rating.got_break is null then
      continue;
    end if;

    insert into employee_events (
      org_id, employee_id, location_id, occurred_on, kind,
      score, shift, position, detail,
      author_employee_id, created_by, source
    ) values (
      v_report.org_id, v_rating.employee_id, v_report.location_id,
      v_report.report_date, 'shift',
      v_rating.score, v_report.shift, v_rating.position,
      nullif(btrim(coalesce(v_rating.note, '')), ''),
      v_report.supervisor_employee_id, auth.uid(), 'app'
    )
    returning id into v_event_id;

    v_ratings := v_ratings + 1;

    -- ---- the missed break is RECORDED, and pays nothing --------------------
    -- 087. This used to insert a `break_premiums` row decided `owed`, which is
    -- the line Mark struck out: "I don't think the app should automatically add
    -- premium pay - the need for it should be suggested in Timesheets and
    -- something the user has to click to make happen."
    --
    -- That is already how Timesheets works and always has been. `ShiftPremium`
    -- appears on a row whenever the workday carries a finding — derived from
    -- the PUNCHES by `assessWorkday`, on every render, never stored (decision
    -- 3) — and a human picks owed / waived / not owed and types the reason 032
    -- requires for the first. So the suggestion happens whether or not this
    -- function writes anything, and what this was doing was pre-empting that
    -- judgement with the conservative answer before anybody had looked at the
    -- punches.
    --
    -- The supervisor's testimony is not lost. It stays on
    -- `shift_report_ratings` and travels in the emailed report; what it no
    -- longer does is DECIDE.
    if v_rating.got_break is false then
      v_breaks := v_breaks + 1;
    end if;

    -- `break_premium_id` is deliberately NOT set: nothing here creates a
    -- premium any more. The column stays, and 072's reopen still clears one,
    -- which is what keeps a report sent BEFORE 086 reversible.
    update shift_report_ratings
       set employee_event_id = v_event_id
     where id = v_rating.id;
  end loop;

  -- ---- counts → production_schedule_items ---------------------------------
  -- 044's whitelist shape: `made` and `leftover` and the two author columns,
  -- nothing else. `par`, `par_source` and every cost column are unreachable
  -- from here by construction, exactly as they are from `set_schedule_actual`.
  for v_count in
    select c.* from shift_report_counts c
     where c.report_id = p_report_id
       and (c.made is not null or c.leftover is not null)
  loop
    update production_schedule_items
       set made       = coalesce(v_count.made, made),
           leftover   = coalesce(v_count.leftover, leftover),
           counted_by = auth.uid(),
           counted_at = now()
     where id = v_count.schedule_item_id;

    if found then
      v_counts := v_counts + 1;
    end if;
  end loop;

  -- ---- yields → production_batches ----------------------------------------
  for v_batch in
    select b.* from shift_report_batches b
     where b.report_id = p_report_id
  loop
    update production_batches
       set yield_count = coalesce(v_batch.yield_count, yield_count),
           yield_size  = coalesce(v_batch.yield_size,  yield_size),
           yield_unit  = coalesce(v_batch.yield_unit,  yield_unit),
           -- 153: the day's total, from the Donut batches page.
           batch_count = coalesce(v_batch.batch_count, batch_count),
           -- A count entered IS the batch done; an explicit status still wins.
           status      = coalesce(v_batch.status,
                                  case when v_batch.batch_count is not null
                                       then 'complete' end,
                                  status),
           notes       = coalesce(nullif(btrim(coalesce(v_batch.notes, '')), ''), notes)
     where id = v_batch.batch_id;

    if found then
      v_batches := v_batches + 1;
    end if;
  end loop;

  update shift_reports
     set status  = 'sent',
         sent_at = now(),
         sent_by = auth.uid(),
         sent_receipt = jsonb_build_object(
           'ratings', v_ratings,
           'breaks',  v_breaks,
           'counts',  v_counts,
           'batches', v_batches,
           'skipped', v_skipped
         )
   where id = p_report_id;

  return jsonb_build_object(
    'report_id', p_report_id,
    'ratings', v_ratings,
    'breaks',  v_breaks,
    'counts',  v_counts,
    'batches', v_batches,
    'skipped', v_skipped
  );
end;
$$;
-- 002's rule: `create or replace` keeps existing grants, but state them anyway
-- so a fresh replay of the migrations lands in the same place as production.
revoke all on function public.submit_shift_report(uuid) from public;
revoke all on function public.submit_shift_report(uuid) from anon;
grant execute on function public.submit_shift_report(uuid) to authenticated;

create or replace function public.reopen_shift_report(p_report_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report   shift_reports%rowtype;
  v_rating   record;
  v_count    record;
  v_batch    record;
  v_events   integer := 0;
  v_premiums integer := 0;
  v_counts   integer := 0;
  v_batches  integer := 0;
  v_kept     jsonb := '[]'::jsonb;
  v_name     text;
begin
  select * into v_report from shift_reports where id = p_report_id;

  if v_report.id is null then
    raise exception 'No such shift report';
  end if;

  if v_report.org_id not in (select user_org_ids()) then
    raise exception 'Not your organisation';
  end if;

  -- A manager reopens any report; a supervisor or purchaser only their OWN —
  -- the author rule every other shift_reports policy and 070's submit use.
  if not (
    user_has_role(v_report.org_id, array['owner', 'admin'])
    or (
      user_has_role(v_report.org_id, array['purchaser', 'supervisor'])
      and v_report.created_by = auth.uid()
    )
  ) then
    raise exception 'only a manager, or the supervisor who wrote it, can reopen a sent report';
  end if;

  if v_report.status <> 'sent' then
    raise exception 'That report is already a draft';
  end if;

  -- ---- the HR rows the flush created ---------------------------------------
  for v_rating in
    select * from shift_report_ratings
     where report_id = p_report_id
       and (employee_event_id is not null or break_premium_id is not null)
  loop
    if v_rating.employee_event_id is not null then
      delete from employee_events where id = v_rating.employee_event_id;
      if found then v_events := v_events + 1; end if;
    end if;

    if v_rating.break_premium_id is not null then
      -- A paid fortnight is not ours to edit. Leave it, name it, carry on —
      -- and leave the POINTER too, so the row still says which premium it
      -- produced rather than losing the link along with the ability to undo it.
      if period_editable_on(v_report.org_id, v_report.report_date) then
        delete from break_premiums where id = v_rating.break_premium_id;
        if found then v_premiums := v_premiums + 1; end if;
      else
        select coalesce(nickname, first_name) || ' ' || last_name into v_name
          from employees where id = v_rating.employee_id;
        v_kept := v_kept || jsonb_build_object(
          'kind', 'premium',
          'employee', coalesce(v_name, 'someone'),
          'reason', 'that pay period is closed, so the premium was left in place'
        );
        continue;
      end if;
    end if;

    update shift_report_ratings
       set employee_event_id = null,
           break_premium_id  = null
     where id = v_rating.id;
  end loop;

  -- ---- the counts it poured onto the schedule ------------------------------
  for v_count in
    select c.* from shift_report_counts c
     where c.report_id = p_report_id
       and (c.made is not null or c.leftover is not null)
  loop
    -- ONLY IF THE LINE STILL HOLDS WHAT WE WROTE. `is not distinct from` so a
    -- null on either side compares properly rather than yielding null.
    update production_schedule_items li
       set made       = null,
           leftover   = null,
           counted_by = null,
           counted_at = null
     where li.id = v_count.schedule_item_id
       and li.made     is not distinct from v_count.made
       and li.leftover is not distinct from v_count.leftover;

    if found then
      v_counts := v_counts + 1;
    else
      select i.item_name into v_name
        from production_schedule_items i where i.id = v_count.schedule_item_id;
      v_kept := v_kept || jsonb_build_object(
        'kind', 'count',
        'item', coalesce(v_name, 'a line'),
        'reason', 'somebody has counted it since, so their figure was left alone'
      );
    end if;
  end loop;

  -- ---- and the yields onto the batches -------------------------------------
  for v_batch in
    select b.* from shift_report_batches b where b.report_id = p_report_id
  loop
    update production_batches pb
       set yield_count = null,
           yield_size  = null,
           yield_unit  = null
     where pb.id = v_batch.batch_id
       and pb.yield_count is not distinct from v_batch.yield_count
       and pb.yield_size  is not distinct from v_batch.yield_size;

    if found then v_batches := v_batches + 1; end if;

    -- 153: the total, on the same terms — only if nobody has changed it since.
    if v_batch.batch_count is not null then
      update production_batches pb
         set batch_count = null
       where pb.id = v_batch.batch_id
         and pb.batch_count = v_batch.batch_count;
    end if;
  end loop;

  -- ---- the report itself: EVERY stamp, not just the status ------------------
  -- A row reading `draft` while still claiming it was emailed on Friday is the
  -- record disagreeing with itself — 059's Reopen clears all four of its
  -- columns together for the same reason. The `task_*` flags stay: paper that
  -- came out of a printer did not go back in.
  --
  -- EXCEPT THE FACT THAT THE TEAM WAS TOLD (107). `emailed_at` is cleared with
  -- the rest, but when it was set its value moves to `previously_emailed_at`
  -- first, so the next Send knows its email CORRECTS one people have read. A
  -- report reopened after a failed mail keeps the older value rather than
  -- losing it — coalesce, newest first.
  update shift_reports
     set previously_emailed_at = coalesce(emailed_at, previously_emailed_at),
         status        = 'draft',
         sent_at       = null,
         sent_by       = null,
         sent_receipt  = null,
         emailed_at    = null,
         emailed_by    = null,
         email_receipt = null
   where id = p_report_id;

  return jsonb_build_object(
    'report_id', p_report_id,
    'events_removed',   v_events,
    'premiums_removed', v_premiums,
    'counts_reverted',  v_counts,
    'batches_reverted', v_batches,
    'kept', v_kept
  );
end;
$$;

revoke all on function public.reopen_shift_report(uuid) from public;
revoke all on function public.reopen_shift_report(uuid) from anon;
grant execute on function public.reopen_shift_report(uuid) to authenticated;


-- ----------------------------------------------------------------------------
-- 7. The donuts on the batch log today (Mark, 2026-09-30) — seasonal, and
--    changed from each element's Kitchens table from here on.
-- ----------------------------------------------------------------------------
insert into production_element_locations (org_id, element_id, location_id)
select e.org_id, e.id, l.id
  from production_elements e
  join locations l on l.org_id = e.org_id and l.code in ('DF01', 'DF02')
 where e.name in ('Raised Donut', 'Vanilla Cake Donut', 'Pumpkin Cake Donut',
                  'Coffee Cake Donut', 'Old Fashioned Donut', 'Mochi Donut',
                  'Apple Fritter', 'Cinnamon Roll')
   and e.is_active
on conflict (element_id, location_id) do nothing;

update production_element_locations el
   set on_batch_log = true,
       is_active    = true
  from production_elements e, locations l
 where e.id = el.element_id
   and l.id = el.location_id
   and l.code in ('DF01', 'DF02')
   and e.name in ('Raised Donut', 'Vanilla Cake Donut', 'Pumpkin Cake Donut',
                  'Coffee Cake Donut', 'Old Fashioned Donut', 'Mochi Donut',
                  'Apple Fritter', 'Cinnamon Roll')
   and e.is_active;
